In [2]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt
plt.style.use('seaborn')

In [3]:
df = pd.read_csv('/Users/alexandrabruno/Documents/flatiron/data/modeling_data1.csv')

In [9]:
mm = pd.read_csv('/Users/alexandrabruno/Documents/flatiron/data/test.csv')

In [8]:
df

,YEAR,STATE,AGE,RTE_CHL,RTE_GON,PRC_BLK,PRC_WHT,PRC_HISP,PRC_OTHER
0,2018,Alabama,35 to 39,115.1,79.0,0.038585,0.046316,0.066667,0.125000
1,2018,Alabama,15 to 19,653.5,325.5,0.025287,0.017949,0.046875,0.105263
2,2018,Alabama,20 to 24,1705.9,657.8,0.102151,0.085202,0.145833,0.130435
3,2018,Alabama,25 to 29,4586.4,1151.1,0.148607,0.138211,0.203390,0.090909
4,2017,Alabama,35 to 39,146.6,70.9,0.049419,0.050968,0.066667,0.090909
...,...,...,...,...,...,...,...,...,...
1989,2004,Wisconsin,20 to 24,1119.9,239.4,0.095238,0.069610,0.150000,0.052632
1990,2004,Wisconsin,25 to 29,2689.6,584.1,0.120000,0.120339,0.275862,0.266667
1991,2017,Wyoming,20 to 24,1122.2,270.0,0.500000,0.090164,0.117647,0.250000
1992,2016,Wyoming,25 to 29,2603.4,143.0,0.333333,0.146853,0.200000,1.000000
1993,2004,Wyoming,20 to 24,722.0,74.2,0.200000,0.130909,0.241379,0.181818

In [15]:
# Get indexes where name column has value PWGTP
indexNames = mm[mm['cause'] == 'All causes'].index
 
# Delete these row indexes from dataFrame
mm.drop(indexNames, inplace=True)

In [17]:
del mm['upper']
del mm['measure']
del mm['sex']
del mm['lower']

In [13]:
mm = mm.rename(columns = {'location':'STATE','age':'AGE','year':'YEAR'})

In [19]:
mm = mm.rename(columns = {'val':'DEATH_RTE'})

In [21]:
df = pd.merge(mm, df,  how='left', left_on=['STATE','YEAR','AGE'], right_on = ['STATE','YEAR','AGE'])

In [24]:
df.dropna(inplace = True)

In [25]:
df

,STATE,AGE,cause,metric,YEAR,DEATH_RTE,RTE_CHL,RTE_GON,PRC_BLK,PRC_WHT,PRC_HISP,PRC_OTHER
0,North Carolina,15 to 19,Maternal disorders,Rate,2011,13.022308,703.9,192.3,0.028896,0.020360,0.062257,0.046512
1,North Carolina,20 to 24,Maternal disorders,Rate,2011,11.677995,1720.5,476.6,0.112000,0.090957,0.202765,0.179775
2,North Carolina,25 to 29,Maternal disorders,Rate,2011,8.313170,5021.5,1043.5,0.125828,0.104752,0.171315,0.188119
4,North Carolina,35 to 39,Maternal disorders,Rate,2011,36.753262,119.5,46.5,0.035982,0.054637,0.063636,0.049383
13,Nebraska,20 to 24,Maternal disorders,Rate,2012,14.294244,1181.0,230.7,0.125000,0.068182,0.128205,0.111111
...,...,...,...,...,...,...,...,...,...,...,...,...
4888,New Mexico,35 to 39,Maternal disorders,Rate,2018,46.163167,412.3,223.3,0.062500,0.042895,0.062500,0.108108
4890,New York,15 to 19,Maternal disorders,Rate,2018,37.499354,741.9,144.3,0.006809,0.004302,0.011009,0.012121
4891,New York,20 to 24,Maternal disorders,Rate,2018,20.765889,1623.6,256.1,0.035197,0.035509,0.039652,0.047817
4892,New York,25 to 29,Maternal disorders,Rate,2018,25.222863,3432.9,460.4,0.073922,0.076442,0.069094,0.067961
4894,New York,35 to 39,Maternal disorders,Rate,2018,30.730396,207.6,40.6,0.074756,0.085239,0.085453,0.062500

In [26]:
df.columns

Index(['STATE', 'AGE', 'cause', 'metric', 'YEAR', 'DEATH_RTE', 'RTE_CHL',
       'RTE_GON', 'PRC_BLK', 'PRC_WHT', 'PRC_HISP', 'PRC_OTHER'],
      dtype='object')

In [30]:
f = 'DEATH_RTE~YEAR+RTE_CHL+RTE_GON+PRC_BLK+PRC_WHT+PRC_HISP'

In [33]:
model = (formula=f, data=df).fit()

NameError: name 'PanelOLS' is not defined

In [32]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              DEATH_RTE   R-squared:                       0.101
Model:                            OLS   Adj. R-squared:                  0.098
Method:                 Least Squares   F-statistic:                     37.27
Date:                Sat, 13 Feb 2021   Prob (F-statistic):           5.04e-43
Time:                        13:30:55   Log-Likelihood:                -8302.1
No. Observations:                1994   AIC:                         1.662e+04
Df Residuals:                    1987   BIC:                         1.666e+04
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -1001.7821    179.257     -5.589      0.000   -1353.334    -650.230
YEAR           0.5119      0.089      5.748      0.000       0.337       0.687
RTE_CHL       -0.0056      0.001     -8.678      0.000      -0.007      -0.004
RTE_GON        0.0225      0.003      8.638      0.000       0.017       0.028
PRC_BLK      -43.1865      7.060     -6.117      0.000     -57.033     -29.340
PRC_WHT       17.4782     14.274      1.224      0.221     -10.515      45.472
PRC_HISP      -7.7594      9.385     -0.827      0.408     -26.165      10.646
==============================================================================
Omnibus:                     1178.501   Durbin-Watson:                   1.782
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            10719.296
Skew:                           2.700   Prob(JB):                         0.00
Kurtosis:                      12.993   Cond. No.                     1.36e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.36e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""